# Generated by Django 6.0.1 on 2026-02-08 17:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
